spring.application.name=FrontOffice

# Configuration du serveur
server.port=${PORT:8080}

# Configuration de la base de donnees PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/frontoffice
spring.datasource.username=postgres
spring.datasource.password=manjaka
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration des connexions
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Configuration des ressources statiques
spring.web.resources.static-locations=classpath:/statics/
spring.mvc.static-path-pattern=/statics/**

spring.profiles.active=prod